Classification:
  distance: 80
  prominence: 0.25
  tdsInspectEnd: 45
  tdsInspectStart: 10
  threshold: 0.005
  width: 19
Export:
  filename: data.dat
  saveDir: C:\Users\TeraSmart-PC\Documents\TheaPython\TQC\qcData
QC:
  allowedErrordB: 1.25
  chipsPerWafer: 10000
  handlingTime: 2s
  lotNum: 1
  lowerFreqBound: 0.5
  maxViolations: 7
  qcAverages: 15
  qcSaveDir: C:\Users\TeraSmart-PC\Documents\TheaPython\TQC\qcData
  sensorId: 1
  stdRefDir: C:\Users\TeraSmart-PC\Documents\TheaPython\TQC\Resources\StandardReferences
  stdRefFileName: 2022-04-15\22-04-15T123926_T_NIL_RH_NIL_PID_NIL_SN_1_None_Reference.txt
  upperFreqBound: 0.9
  waferId: AA0001
Robots:
  baudrate: 115200
  port: COM5
  timeout: 10
Spectrometer:
  name: TERASMART
  systemNum: 0
TScan:
  begin: -271
  numAvgs: 5
  window: 400
Temp:
  airFileNames:
  - Air.txt
  sensorFileNames:
  - Sensor1.txt
