Classification:
  distance: 80
  prominence: 0.25
  tdsInspectEnd: 100
  tdsInspectStart: 50
  threshold: 0.005
  width: 500
Export:
  filename: data.dat
  saveDir: C:\Users\TeraSmart\Documents\API_MenloSystem\RamGlobalSystem\TQC\Export
QC:
  allowedErrordB: 1.25
  chipsPerWafer: 75
  handlingTime: 2s
  lowerFreqBound: 0.5
  maxViolations: 7
  qcAverages: 10
  qcSaveDir: C:\Users\TeraSmart\Documents\API_MenloSystem\RamGlobalSystem\TQC\Export
  sensorId: 1
  stdRefFilePath: C:\Users\TeraSmart\Documents\THEA_Python\TQC\Resources\StandardReferences\071221T151127_WID_W0_SN_1_STANDARD_Reference.txt
  upperFreqBound: 0.9
  waferId: W0000
Spectrometer:
  name: TERASMART
  systemNum: 0
TScan:
  begin: -320
  numAvgs: 10
  window: 400
Temp:
  airFileNames:
  - Air_singleshot.txt
  sensorFileNames:
  - F1_singleshot.txt
Robots:
  Port: COM6
  baudrate: 115200
