
Export:
  filename: data.dat
  saveDir: C:\Users\TeraSmart\Documents\PythonSoftwareTestExportData\TimelapseExport
Spectrometer:
  name: TERASMART
  systemNum: 9
TScan:
  begin: -271
  numAvgs: 10
  window: 400     
Timelapse:
  interval: 5s # units of time - s, min, hr, day ...
  frames: 3 # zero to run out max storage, enter int for other specified values.
  maxStorage: 2GB # max storage for timelapse session - kB, MB, GB
  _filesize : 606 kB # typical filesize - private!
  numDisplayDataSeries: 5
TemperatureSensor:
  port: COM6
  baudrate: 115200
  timeout: 2
  scrollLength: 10
  samplingRate: 0.75 
